linters:
  rubocop:
    display_cop_names: true
    config: "./rubocop.yml"

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

AllCops:
  NewCops: disable

Style/ANewCop:
  Enabled: false